### ISSUE TITLE
dokuwikixmlrpc python module

### ISSUE THREAD

**Issue by th3bl4cksmith** [kynan/dokuvimki#12]
I've tried to use DokuVimKi in Python 3 and 2.7 virtualenvs. Also installed dokuwikixmlrpc using 'easy_install dokuwikixmlrpc' for both.

When starting :DokuVimKi In the Python 2.7 virtualenv I get 

```
Error detected while processing /home/foo/.vim/plugged/dokuvimki/plugin/dokuvimki.vim:                                     
line 1050:
DokuVimKi Error: The dokuwikixmlrpc python module is missing!
Error detected while processing function <SNR>8_lod_cmd:
line    3:
dokuwikixmlrpc python module missing!
```
In the Python 3 virtualenv I get:
```
Error detected while processing /home/foo/.vim/plugged/dokuvimki/plugin/dokuvimki.vim:                                     
line 1050:
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load                                                        
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked                                               
  File "<frozen importlib._bootstrap>", line 894, in _find_spec                                                            
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec                                                   
  File "<frozen importlib._bootstrap_external>", line 1131, in _get_spec                                                   
  File "<frozen importlib._bootstrap_external>", line 1112, in _legacy_get_spec                                            
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader                                                      
  File "<frozen importlib._bootstrap_external>", line 544, in spec_from_file_location                                      
  File "/home/foo/py3env/lib/python3.6/site-packages/dokuwikixmlrpc-2010_07_19-py3.6.egg/dokuwikixmlrpc.py", line 114      
    except xmlrpclib.Fault, fault:
                          ^
SyntaxError: invalid syntax
Error detected while processing function <SNR>8_lod_cmd:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'dokuvimki' is not defined
```
The XML-RPC interface is enabled on the wiki site and all the configuration details are correct. I'm out of ideas as to what the problem could be and how to fix this, so any help would be greatly appreciated.

**Comment by kynan** [comment]
Vim does not support virtualenv out of the box. You need to use a plugin like https://github.com/plytophogy/vim-virtualenv to make that work.

Any reason you're using `easy_install`? It was deprecated years ago in favour of `pip`.
