### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by eater** [kynan/dokuvimki#9]
Just installed and trying to run `:DokuVimKi` : 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 945, in dokuvimki
  File "<string>", line 51, in __init__
  File "<string>", line 107, in xmlrpc_init
  File "/usr/local/lib/python2.7/dist-packages/dokuwikixmlrpc.py", line 113, in __init__
    self.dokuwiki_version = self._dokuwiki_version()
  File "/usr/local/lib/python2.7/dist-packages/dokuwikixmlrpc.py", line 145, in _dokuwiki_version
    return self._xmlrpc.dokuwiki.getVersion()
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1331, in single_request
    response.msg,
xmlrpclib.ProtocolError: <ProtocolError for localhost:8080/dokuwiki//lib/exe/xmlrpc.php?p=password&u=eater: 403 Forbidden>                        
```

**Comment by eater** [comment]
I had remoteuser misconfigured in the dokuwiki config -- never mind!
